name: Sync images

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 20
        env:
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          DOCKERIO_USERNAME: ${{ secrets.DOCKERIO_USERNAME }}
          DOCKERIO_PASSWORD: ${{ secrets.DOCKERIO_PASSWORD }}
